# Generated by Django 4.2.7 on 2025-11-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_bio_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
    ]
