# Generated by Django 4.2.7 on 2025-11-28 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_last_login_ip_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
